# from https://github.com/gwgundersen/blog-theme/blob/master/_config.yml
highlighter: rouge
environment: prod
show_author: false
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
#katex:
#  js_path: "assets"  # Path used to search for katex.min.js
